### Importações

In [153]:
from pathlib import Path
from database import banco
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

PASTA_RAIZ = Path.cwd().parent
PASTA_SQL_GOLD = PASTA_RAIZ / "sql" / "gold"

lista_perguntas = [
    ("pergunta_1", "top5_orgaos_custo_total"),
    ("pergunta_2", "top3_destinos_custo_medio"),
    ("pergunta_3", "viagem_maior_duracao"),
    ("pergunta_4", "tipo_pagamento_valor_medio"),
    ("pergunta_5", "meio_transporte_utilizacao"),
    ("pergunta_6", "destino_uf_frequencia"),
    ("pergunta_7", "orgaos_pagadores_custo_total"),
]
# Ajustando a visuaçização do Pandas, devido aos valores serem altos e acabarem dificultando a visualização
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [131]:
def carregar_sql(caminho):
    with open(caminho, "r", encoding="utf-8") as arquivo:
        return arquivo.read()

In [ ]:
def criar_gold_view(conexao, nome_tabela, sql):

    print(f"Criando a GOLD da tabela gold_{nome_tabela}")
    banco.executar(conexao, f"DROP TABLE IF EXISTS gold_{nome_tabela}")
    banco.executar(conexao, f"CREATE TABLE gold_{nome_tabela} AS {sql}")
   
    print(f"Criando a VIEW da tabela {nome_tabela}")
    banco.executar(conexao, f"DROP VIEW IF EXISTS vw_{nome_tabela}")
    banco.executar(conexao, f"CREATE VIEW vw_{nome_tabela} AS {sql}")

In [135]:
def analisar(pergunta):
    conexao = None

    try:
        conexao = banco.conectar()
        caminho_sql = PASTA_SQL_GOLD / f"{lista_perguntas[pergunta-1][0]}.sql"
        sql = carregar_sql(caminho_sql)
        df = pd.read_sql(sql, conexao)

    except Exception as erro:
        print("[ERRO] Algo deu errado:", erro)
        raise

    finally:
        if conexao:
            conexao.close()

    return df

# **Perguntas a responder:**

1. Os 5 órgãos com maior custo total?
2. Os 3 destinos com maior custo médio por viagem?
3. A viagem de maior duração e seu custo total?
4. Qual o tipo de pagamento com maior valor médio?
5. Qual o meio de transporte mais usado nos trechos?
6. Qual UF de destino aparece em mais trechos?
7. Qual órgão pagou mais no total?

### Pergunta_1: Os 5 órgãos com maior custo total?

In [136]:
df = analisar(1)
df

                              nome_orgao_superior    custo_total
0       MINISTÉRIO DA JUSTIÇA E SEGURANÇA PÚBLICA 486,933,121.65
1                            MINISTÉRIO DA DEFESA 156,070,304.49
2                          MINISTÉRIO DA EDUCAÇÃO 111,291,349.34
3  MINISTÉRIO DO MEIO AMBIENTE E MUDANÇA DO CLIMA  49,697,710.16
4                MINISTÉRIO DA PREVIDÊNCIA SOCIAL  40,417,309.06

### Pergunta_2: Os 3 destinos com maior custo médio por viagem?

In [154]:
try:
    conexao = banco.conectar()
    caminho_sql = PASTA_SQL_GOLD / f"{lista_perguntas[1][0]}.sql"
    sql = carregar_sql(caminho_sql)
    criar_gold_view(conexao, lista_perguntas[1][1], sql)

except Exception as erro:
    print("[ERRO] Algo deu errado:", erro)
    raise

finally:
    if conexao:
        conexao.close()
df = analisar(2)
df

Criando a GOLD da tabela gold_top3_destinos_custo_medio
Criando a VIEW da tabela top3_destinos_custo_medio

                                            destinos      media
0  BRASÍLIA/DF, BRASÍLIA/DF, BRASÍLIA/DF, BRASÍLI... 105,470.37
1              BRASÍLIA/DF, BRASÍLIA/DF, BRASÍLIA/DF 100,317.26
2  BRASÍLIA/DF, BRASÍLIA/DF, BRASÍLIA/DF, BRASÍLI...  97,736.69

### Pergunta_3: A viagem de maior duração e seu custo total?

In [140]:
df = analisar(3)
df

,id_viagem,nome_viajante,data_inicio,data_fim,duracao_dias,valor_total
0,0000000000020699856,LUISANGELA CORREA FRANCO DE FARIA,2025-01-13,2026-01-31,383,0.00

### Pergunta_4: Qual o tipo de pagamento com maior valor médio?

In [ ]:
df = analisar(4)
df

### Pergunta_5: Qual o meio de transporte mais usado nos trechos?

In [ ]:
df = analisar(5)
df

### Pergunta_6: Qual UF de destino aparece em mais trechos?

In [ ]:
df = analisar(6)
df

### Pergunta_7: Qual órgão pagou mais no total?

In [ ]:
df = analisar(7)
df